spring:
  application:
    name: spring-boot-dasar
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bootcamp_db
    username: postgres
    password: 1234

name:
  firstName: Latif
  lastName: irfan

server:
  port: 9090

