spring:
  application:
    name: spring-boot-dasar
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bootcamp_db
    username: postgres
    password: 1234
  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update
    show-sql: true
    generate-ddl: true

header:
  request:
#    api-key: 6b98ebdd-ba06-492c-9d47-3895e190263e
    api-key: ${API_KEY}

name:
  firstName: Latif
  lastName: irfan

server:
  port: 9090

